# use the latest ubuntu environment (18.04) available on travis
dist: xenial
sudo: required
language: go
os:
- linux

go:
  - 1.13.x



before_install:
  - sudo curl -L -o /usr/local/lib/libzenohc.so https://www.dropbox.com/s/c6l18wbtk4eggpt/libzenohc.so
  - go get github.com/atolab/yaks-go
  - go get github.com/google/uuid
  - go get github.com/sirupsen/logrus


install:
  - go build github.com/eclipse-fog05/sdk-go/fog05sdk