# use the latest ubuntu environment (18.04) available on travis
dist: xenial
sudo: required
language: go
os:
- linux

go:
  - 1.13.x



before_install:
  - sudo curl -L -o /usr/local/lib/libzenohc.so https://www.dropbox.com/s/c6l18wbtk4eggpt/libzenohc.so


install:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel